Talk layoutの実装
KU-eSports/kuest-streaming pull request #58
Opened 2022-10-21 15:09 UTC by NYA0321

##変更点
ラフをもとにレイアウトの作成

##これから必要なこと
ちゃぬさんにまかせた！

2022-10-23 09:11 UTC, secchanu requested changes
### z-indexを減らしましょう

z-indexの調整は最終手段です
基本的にhtml上で上のものから重なっていくので、できるだけ要素の順番で対応しましょう
その方が要素がレイヤー順に並んでいて見やすくなるメリットもあります

2022-10-24 01:38 UTC, Tooooomo requested changes
css,htmlはせっちゃんに任せて自分からはデザイン面中心にレビューを

## フレームまわり
問題ないと思いますが一つだけ  
左下のロゴの傾きの軸と回転の軸がそろっていたほうが見栄えがいいかと  

## アイコンと名前
アイコンの大きさをもう二回りくらい大きくしてほしいです  
今のままだとネームプレートの方が存在感があって少しアンバランスに見えます  
フレームとの間の余白も見ながら調整してみてください

2022-10-30 12:54 UTC, Tooooomo reviewed
デザイン面ではOKです
これでいきましょう

2022-10-30 12:55 UTC, secchanu requested changes
voiceのテスト用の名前を"yyyyyyyy"にして確認してみて

2022-10-30 13:04 UTC, Tooooomo approved these changes

2022-10-30 13:09 UTC, secchanu approved these changes

2022-10-30 13:10 UTC, merged