add overlay
KU-eSports/kuest-streaming pull request #59
Opened 2022-11-01 15:49 UTC by Tooooomo

ハイライト2種完成しました
確認と追加・修正必要ならその旨お願いします

#45 にラフと使用例乗ってます

2022-11-02 05:46 UTC, ykmtsd commented
今日のハイライトはdaily highlightじゃなくてtoday's highlightのほうがいいと思います。dailyには毎日というニュアンスがあるので少し不自然に感じます。

2022-11-02 14:58 UTC, secchanu requested changes
externalは追跡しない予定なので.gitignoreに追加してください

2022-11-04 14:58 UTC, Tooooomo commented
## 修正
### external
gitignoreに追加しておきました

### overlay
複数形のhighlightsに修正
today'sはフォントの仕様でアポストロフィがきれいに入らないから少し収まり悪いけどof todayに

#### サンプル
![today](https://user-images.githubusercontent.com/104683109/200006410-c642f120-bf7b-4cc6-bec3-536a0f0c5782.png)

2022-11-05 02:20 UTC, ykmtsd approved these changes

2022-11-05 02:21 UTC, merged