waiting layout の実装
KU-eSports/kuest-streaming pull request #63
Opened 2022-11-06 15:15 UTC by NYA0321

##変更点
waiting layout の実装を行いました
ラフ通りにできたと思います

##これから必要なこと
ちゃぬさんお願いします

2022-11-08 00:28 UTC, secchanu requested changes
プロパティ(position, width, heightなど)の順番は大体でいいので揃えましょう(特に同じもの例えばwrapperとか)
見やすくなります

2022-11-08 00:28 UTC, secchanu commented on src/browser/graphics/waiting/css/stickers.css
> +.stikcers {
スペルミス？

2022-11-08 00:28 UTC, secchanu commented on src/browser/graphics/waiting/css/timer.module.css
> +  position: absolute;
ここは`position: absolute;`だけど親要素はstaticのままなのでは

2022-11-08 07:26 UTC, NYA0321 commented
このエラーまた出ました

> git push origin waiting-layout:waiting-layout
remote: error: GH006: Protected branch update failed for refs/heads/waiting-layout.        
remote: error: At least 2 approving reviews are required by reviewers with write access.        
To https://github.com/KU-eSports/kuest-streaming.git
 ! [remote rejected] waiting-layout -> waiting-layout (protected branch hook declined)
error: failed to push some refs to 'https://github.com/KU-eSports/kuest-streaming.git'

2022-11-08 12:15 UTC, secchanu commented
> このエラーまた出ました
> 
> > git push origin waiting-layout:waiting-layout
> > remote: error: GH006: Protected branch update failed for refs/heads/waiting-layout.
> > remote: error: At least 2 approving reviews are required by reviewers with write access.
> > To https://github.com/KU-eSports/kuest-streaming.git
> > ! [remote rejected] waiting-layout -> waiting-layout (protected branch hook declined)
> > error: failed to push some refs to 'https://github.com/KU-eSports/kuest-streaming.git'

どうもpushにも適用されるみたいなのでハイフン付きのものは除外しました
これでできそう？

2022-11-08 23:22 UTC, secchanu commented
直せたら左上のReviewersからRe-request reviewしてね

2022-11-09 19:21 UTC, Tooooomo approved these changes

2022-11-10 08:47 UTC, secchanu approved these changes

2022-11-10 08:48 UTC, merged